name: Test

on: pull_request

jobs:
  ESLint:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout source code.
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn run lint
        env:
          CI: true